FROM oraclelinux:8 AS oracle8

# ---------------------------------- Installing dependencies as root ---------------------------------- 
# RUN dnf install -y wget
# RUN dnf install -y wget epel-release git cmake3 gcc-c++ gcc binutils 
RUN dnf install -y wget epel-release git cmake3 gcc-c++ gcc binutils \
compat-openssl10 libX11-devel libXpm-devel libXft-devel libXext-devel \ 
gsl-devel openssl-devel wget bzip2-devel libffi-devel xz-devel sqlite-devel \
ncurses ncurses-devel make xz libzstd libzstd-devel which rsync \
nmap-ncat chrony

RUN dnf install -y oracle-epel-release-el8
RUN dnf config-manager --enable ol8_codeready_builder
RUN dnf install -y hdf5 hdf5-devel

# ---------------------------------- Create Agilepy user ---------------------------------- 
RUN useradd usercosi
USER usercosi
WORKDIR /home/usercosi
RUN mkdir -p /home/usercosi/dependencies
SHELL ["/bin/bash", "--login", "-c"]

USER root 

#ARM
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh
RUN chmod +x Miniconda3-latest-Linux-aarch64.sh
RUN ./Miniconda3-latest-Linux-aarch64.sh -b -p /opt/conda 
RUN rm Miniconda3-latest-Linux-aarch64.sh

WORKDIR /cosi
RUN chown -R usercosi:usercosi /cosi/


USER usercosi

RUN export PATH=$PATH:/opt/conda/bin && conda config --append channels conda-forge && conda config --set channel_priority strict &&  conda create -n cosi python=3.10 pip jupyter

RUN git clone https://github.com/cositools/cosipy.git /cosi/cosipy

RUN export PATH=$PATH:/opt/conda/bin && source activate cosi && cd /cosi/cosipy && git checkout develop && pip install -e . && pip install ipykernel && python -m ipykernel install --user --name cosi

USER root
RUN  mkdir /shared_dir
RUN chown -R usercosi:usercosi /shared_dir
RUN  mkdir /data01
RUN chown -R usercosi:usercosi /data01
RUN  mkdir /data02
RUN chown -R usercosi:usercosi /data02
COPY ./entrypoint.sh /home/usercosi/entrypoint.sh
RUN chmod +x /home/usercosi/entrypoint.sh

USER usercosi
RUN mkdir /home/usercosi/workspace
ENV PATH="/opt/conda/bin:$PATH"
#ENTRYPOINT ["bash", "/home/usercosi/entrypoint.sh"]
